### ISSUE TITLE
Mousewheel support

### ISSUE THREAD

**Issue by ghost** [simmel/urxvt-resize-font#10]
Any idea on how to add mousewheel support to use `C-<scroll up>` and `C-<scroll down>` to increase/decrease font sizes?

**Comment by ghost** [comment]
No more soy for you!

**Comment by simmel** [comment]
='(

**Comment by ghost** [comment]
:joy_cat: :cocktail:

**Comment by simmel** [comment]
Uh, I see now that my mail never reached github. My original comment before closing this issue was:

Sorry, no idea :(

I saw something about mouse reporting, that might be something to
look into.
Please document your findings here.

Good luck!
