### ISSUE TITLE
Wayland support

### ISSUE THREAD

**Issue by globalviking** [simmel/urxvt-resize-font#12]
Hi simmel,

I hope you are having a great day!

I am trying to get this to work in Wayland with no success. My guess is that keysym doesn't work with it.

Do you know if there is any way to get this to work on Wayland?

Thanks for the great extension!

**Comment by simmel** [comment]
Hey Ivar!

Thanks, no problem!

Does any other urxvt extension that uses keysym work?

**Comment by globalviking** [comment]
Hello,

I tried running X11 and that didn't work either.
So it may have nothing to do with Wayland.

I will try to install another extension to troubleshoot.

🖥️🔨

**Comment by globalviking** [comment]
Closing this for now since I am not using urxvt anymore and because my issue may not have had anything to do with Wayland.

Have a great day!
