### ISSUE TITLE
Can I use other fonts to resize?

### ISSUE THREAD

**Issue by edn9** [simmel/urxvt-resize-font#15]
Looks like I cant change, I was trying those but only Inconsolata work.

> !URxvt.font:                       9x15,xft:TerminessTTFNerdFontMono
> URxvt.font: 		           xft:Inconsolata:pixelsize=15
> !URxvt.font: 			   xft:curie:pixelsize=20
> !URxvt.font: 		           xft:tewi:pixelsize=10

**Comment by simmel** [comment]
`!` is a comment in `.Xresources` so Inconsolata is the only font you're trying to use.

I'm not sure if urxvt picks the first or last font defined either.

**Comment by edn9** [comment]
@simmel oh yes simmel I know, i was trying those fonts to see if they can scale too (thats why the !), but only the Inconsolata work, idk if its about the script, the font (some fonts like tewi cant really change size, bitmap monospaced font), but I wonder if this script will work fine with others fonts too.

**Comment by simmel** [comment]
On Thu, 2018-06-21 at 09:37:17 +0000, Necronoise wrote:
>@simmel oh yes simmel I know, i was trying those fonts to see if they can scale too, but only the Inconsolata work, idk if its about the script, the font (some fonts like tewi cant really change size, bitmap monospaced font), but I wonder if this script will work fine with others fonts too.

I think most fonts will work, I don't have the conf here so I can't show 
you sadly.
