### ISSUE TITLE
Clipboard Controls Quit Working

### ISSUE THREAD

**Issue by odysseyalive** [simmel/urxvt-resize-font#20]
I've been working  out the conflict that's causing my custom clipboard keys to no longer work after loading this script.  If you have any ideas in the meantime - much appreciated!

! REMAP CLIPBOARD CONTROLS
URxvt.iso14755: false
URxvt.iso14755_52: false
URxvt.keysym.Shift-Control-V: eval:paste_clipboard
URxvt.keysym.Shift-Control-C: eval:selection_to_clipboard

using: 
rxvt-unicode (urxvt256c) v9.22 - released: 2016-01-23
Fedora 31 Repo

**Comment by simmel** [comment]
So sorry that this is happening to you, sounds like a weird issue.

What keys are you pressing?

What do you expect to happen?

What actually happens?

**Comment by odysseyalive** [comment]
This code clippet lives in Xresources.

! REMAP CLIPBOARD CONTROLS
URxvt.iso14755: false
URxvt.iso14755_52: false
URxvt.keysym.Shift-Control-V: eval:paste_clipboard
URxvt.keysym.Shift-Control-C: eval:selection_to_clipboard

I'd wager this is what most people use to wake up copy and paste functionality in Urxvt.  By highlighting text and Shift-Control-C, copies the text to system clipboard.  Shift-Control-V pastes system clipboard into URxvt.

Neither of those controls are working now.  Nothing happens.  Something in your script is overriding all URxvt.keysym statements - not just the ones used for growing, shrinking and resetting font sizes.

**Comment by odysseyalive** [comment]
This was my bad.  I hadn't made friends yet with Urxvt loading of the perl extensions.  I needed to include the default and clipboard packages along with your script:

https://wiki.archlinux.org/index.php/Rxvt-unicode#Changing_font_size_on_the_fly

There is no need to include internel extensions like default and clipboard.  Evidently when adding an external script, they become necessary:

URxvt.perl-ext-common: default,clipboard,resize-font

**Comment by simmel** [comment]
Ah, that was news to me as well!

Good that you could solve it your self and we both learned something in 
the process!
