### ISSUE TITLE
shift ctrl - does not decrease font size

### ISSUE THREAD

**Issue by dman777** [simmel/urxvt-resize-font#22]
Thank you for making this plugin.... I have used URXVT for over 10 years and I refuse to switch from it. However, now that I am getting old now I can not read text as good. This plugin allows me to continue to use my favorite urxvt!

I noticed that `shift ctrl +` was able to enlarge the print. But `shift ctrl -` fails to decrease size. Is there anything I need to change on my end?

**Comment by simmel** [comment]
Hey Darin!

Thank you for that = ) I'm glad to have helped you!

Open a new urxvt window without attaching screen or tmux, run `cat -v` 
and hold type ctrl and type a + (I guess you also must hold down shift 
to get a plus?). Paste the output here, please.

**Comment by simmel** [comment]
Err, press ctrl and - that is since that's what's failing = )

Also, please paste the output of `grep -Ei 'keysym|font' ~/.Xresources` 
just for faster troubleshooting.

**Comment by simmel** [comment]
@dman777 how did it work out?

**Comment by dman777** [comment]
Sorry about the late reply. I ended up buying reading glasses instead and now I keep the terminal fonts the stock size :)
