### ISSUE TITLE
instead of resizing, prints the content of Xdefaults to the console

### ISSUE THREAD

**Issue by aleksfadini** [simmel/urxvt-resize-font#24]
I configured my resize hotkey as usual (following arch wiki), my hotkey works but instead of resizing the window, it prints the list of my fonts from Xdefaults.
Interestingly enough, it prints the list correctly modify of the step I wanted up or down according to bigger or smalle hotkey.

Exemple, all my fonts are 10, when pressing the "bigger key", I get this in the terminal:

`$ xft:Inconsolata Nerd Font Mono:size=11, 	xft:Terminess TTF Nerd Font Mono:size=11, 	xft:Source Code Pro:size=11:hinting=true,   	xft:Consolas:size=11:hinting=true, 	xft:DejaVu Sans:size=11:hinting=true, 	xft:UbuntuMono Nerd Font:size=11`

What is happening?

My .Xdefaults relevant snippet:

```
!! Extensions
URxvt.perl-ext-common:	default,matcher,resize-font,url-select,keyboard-select,clipboard
!URxvt.perl-ext-common:	default,resize-font,keyboard-select,clipboard,
URxvt.colorUL:		#4682B4
!! url-select
URxvt.keysym.M-u:	perl:url-select:select_next
URxvt.url-select.launcher: linkhandler
URxvt.url-select.underline: true
!! keyboard-select:
URxvt.keysym.M-Escape: perl:keyboard-select:activate
!! resize-font
URxvt.iso14755: false
URxvt.iso14755_52: false
!URxvt.resize-font.smaller:	C-j
!URxvt.resize-font.bigger:	C-k
URxvt.keysym.C-Shift-J:  resize-font:smaller
URxvt.keysym.C-Shift-K:    resize-font:bigger
URxvt.resize-font.step: 1
```

**Comment by simmel** [comment]
Hi @aleksfadini!

`C-j` is enter/return and `C-k` is "kill until end of line" usually, so that's probably what's happening. For some combinations it doesn't seem to be able to use Shift and I have no idea why. I'm guessing readline or urxvt takes over or lets something other takes priority. ¯\\\_(ツ)\_/¯ 

It's really weird that it prints the fonts though. What's your version of urxvt?:
```terminal
$ urxvt --help 2>&1 | head
```
Can you also paste the output of:
```terminal
$ pacman -Qi urxvt-resize-font-git
```

**Comment by aleksfadini** [comment]
Thank you for looking into this, I'm a bit at a loss. Replying in order:

```
]$ urxvt --help 2>&1 | head
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
Usage: urxvt [options] [-e command args]

where resources (long-options) include:
  termName:                       string
  geometry:                       geometry
  chdir:                          string
  reverseVideo:                   boolean
  loginShell:                     boolean

```

And:
```

$ pacman -Qi urxvt-resize-font-git
Name            : urxvt-resize-font-git
Version         : 27.b593580-1
Description     : An urxvt plugin to adjust the font size on the fly
Architecture    : any
URL             : https://github.com/simmel/urxvt-resize-font
Licenses        : MIT
Groups          : None
Provides        : urxvt-resize-font
Depends On      : rxvt-unicode
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : urxvt-resize-font
Replaces        : None
Installed Size  : 7.18 KiB
Packager        : Unknown Packager
Build Date      : Fri 06 Nov 2020 03:17:46 PM EST
Install Date    : Fri 06 Nov 2020 03:17:50 PM EST
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```


Any ideas? Thanks again.

I should add, I tested control+shift+j or k and it works in urxvt for other hotkeys (such as if I assign it to scrolling up and down).

**Comment by simmel** [comment]
On Sat, 2020-11-07 at 14:13:59 -0800, aleksfadini wrote:
>Thank you for looking into this, I'm a bit at a loss. Replying in order:
>
>```
>]$ urxvt --help 2>&1 | head
>rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
>options: perl,xft,styles,combining,blink,iso14755,unicode3,encodings=eu+vn+jp+jp-ext+kr+zh+zh-ext,fade,transparent,tint,XIM,frills,selectionscrolling,wheel,slipwheel,cursorBlink,pointerBlank,scrollbars=plain+rxvt+NeXT+xterm
>Usage: urxvt [options] [-e command args]
>
>where resources (long-options) include:
>  termName:                       string
>  geometry:                       geometry
>  chdir:                          string
>  reverseVideo:                   boolean
>  loginShell:                     boolean
>
>```

Only difference here is that I have smart-resize enabled, see 
<https://github.com/exg/rxvt-unicode>, and while that could affect this 
issue I doubt it since many of the users of this script are running 
ArchLinux and if ArchLinux doesn't have smart-resize by default I should 
have heard about this earlier.

>And:
>```
>
>$ pacman -Qi urxvt-resize-font-git
>Name            : urxvt-resize-font-git
>Version         : 27.b593580-1
>Description     : An urxvt plugin to adjust the font size on the fly
>Architecture    : any
>URL             : https://github.com/simmel/urxvt-resize-font
>Licenses        : MIT
>Groups          : None
>Provides        : urxvt-resize-font
>Depends On      : rxvt-unicode
>Optional Deps   : None
>Required By     : None
>Optional For    : None
>Conflicts With  : urxvt-resize-font
>Replaces        : None
>Installed Size  : 7.18 KiB
>Packager        : Unknown Packager
>Build Date      : Fri 06 Nov 2020 03:17:46 PM EST
>Install Date    : Fri 06 Nov 2020 03:17:50 PM EST
>Install Reason  : Explicitly installed
>Install Script  : Yes
>Validated By    : None
>```

So this is the latest version which also works for me and others...

**Comment by simmel** [comment]
What's even weirder is that when I updated to the latest urxvt-resize-font (I tested this from a different machine that I usually develop urxvt-resize-font on) your config works.

Can you paste your whole `.Xresources` so I can check if there anything else there which prevents your keybindings from working?

**Comment by aleksfadini** [comment]
Thank you for looking into this with such detail.
Here is my .Xresources:
https://pastebin.com/uvfEHDBG

**Comment by simmel** [comment]
Ah, I found it (and I could reproduce that fonts got printed when pressing the resize buttons = ).

Apparently you can't have tabs in your font defintion, so change it to:
```xdefaults
URxvt.font: xft:JetBrains Mono:size=10, \
xft:Inconsolata Nerd Font Mono:size=10, \
xft:Terminess TTF Nerd Font Mono:size=10, \
xft:Source Code Pro:size=9:hinting=true, \
xft:Consolas:size=9:hinting=true, \
xft:DejaVu Sans:size=9:hinting=true, \
xft:UbuntuMono Nerd Font:size=10
```

**Comment by aleksfadini** [comment]
Thank you so much!!
That did it!

It's one of those things... it would have taken forever to figure out on my own. Thank you for putting the time to test my config and for your awesome plugin. You rock 🚀

**Comment by simmel** [comment]
No problem! Have a great weekend!
