### ISSUE TITLE
Resize fallback fonts

### ISSUE THREAD

**Issue by rtoijala** [simmel/urxvt-resize-font#7]
Hello,
first of all thanks for providing this plugin.

I have multiple fonts defined in my .Xresources (see below).
I would like urxvt-resize-font to resize all of them when I press any of the keysyms.
Currently, only the first is resized.
This means that when e.g. random Unicode characters are displayed at a different size than surrounding text when the characters are not available in the first font.

Screenshot of the issue:
![screenshot](https://cloud.githubusercontent.com/assets/1586926/13673116/4dbc34fe-e6e0-11e5-9916-417a13f96981.png)

Relevant parts of my ~/.Xresources:

```
URxvt.font: xft:Dejavu Sans Mono:pixelsize=12,xft:Consolas:pixelsize=12,xft:Code2000:pixelsize=12,xft:symbola:pixelsize=12
URxvt.perl-ext-common: default,matcher,resize-font
URxvt.resize-font.smaller: C-Down
URxvt.resize-font.bigger: C-Up
URxvt.resize-font.reset: C-Right
URxvt.resize-font.show: R-Left
```

**Comment by simmel** [comment]
Thanks for reporting this bug!

Do you have examples of what kind of unicode characters which aren't
resized correctly? I'm asking so I can test this correctly. 😄

I've never thought about that you could configure multiple fonts tbh = )

**Comment by rtoijala** [comment]
Hi,
basically all characters that are not included in the first font in your .Xresources.
My first font is Dejavu Sans Mono, which does not include e.g. Chinese characters.
For testing I insert them as e.g. Ctrl-Shift-4399 for 䎙. You can also just copy-paste them after googling "Chinese character".
My third font (Code2000) provides the characters, so if resizing fallback-fonts works properly, they appear as large as normal latin characters.

**Comment by simmel** [comment]
Thank you for providing a test case, I'll look into it!

**Comment by simmel** [comment]
I couldn't get `Code2000` to work in urxvt so I used `Droid Sans Fallback` instead.

Can you please try and use HEAD? If that doesn't work, please reopen this issue.

Sorry it took so long to fix (and it's such a small fix, but I didn't know that until I tried to fix it = )!

**Comment by rtoijala** [comment]
Hi,
it seems to work.
Thanks a lot for looking into this.
