### ISSUE TITLE
bigger only works to config size?

### ISSUE THREAD

**Issue by mackenza** [simmel/urxvt-resize-font#8]
Hi, I have my font line in `.Xresources` set to:

```
URxvt.font:xft:Inconsolata:size=12
```

and I notice with my key bindings I can go smaller and bigger but bigger never goes above 12 points. Is this a known thing? Or am I doing something wrong?

**Comment by simmel** [comment]
On Mon, 2016-07-11 at 19:07:49 -0700, Andrew MacKenzie wrote:

> Hi, I have my font line in `.Xresources` set to:
> 
> ```
> URxvt.font:xft:Inconsolata:size=12
> ```

That's supposed to be:

```
urxvt.font: xft:Inconsolata:pixelsize=12
```

Note _pixel_size. No idea why and I haven't found much docs on it.

**Comment by mackenza** [comment]
ok thx... appreciate the response.

**Comment by simmel** [comment]
Note that using `urxvt.font: xft:Inconsolata:size=12` works and should work.

For the difference, see https://github.com/simmel/urxvt-resize-font/pull/2#issuecomment-145445623
